services:
  cassandra:
    image: cassandra:5.0.7
    container_name: cassandra
    ports:
      - "9042:9042"
    environment:
      CASSANDRA_CLUSTER_NAME: "local-cluster"
      CASSANDRA_DC: "datacenter1"
      CASSANDRA_ENDPOINT_SNITCH: "GossipingPropertyFileSnitch"
    command: >
      sh -c "sed -i '/enable_sasi_indexes/d' /etc/cassandra/cassandra.yaml && echo 'sasi_indexes_enabled: true' >> /etc/cassandra/cassandra.yaml && docker-entrypoint.sh cassandra -f"
    # Cassandra стартует долго — нужен большой start_period
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh -e 'SELECT now() FROM system.local' 2>/dev/null || exit 1" ]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 120s

  cassandra-init:
    image: cassandra:5.0.7
    command: >
      cqlsh cassandra -e "
      CREATE KEYSPACE IF NOT EXISTS product_model_ks
      WITH REPLICATION = { 'class' : 'NetworkTopologyStrategy', 'datacenter1' : 1 };"
    depends_on:
      cassandra:
        condition: service_healthy

  liquibase:
    image: liquibase/liquibase:4.29
    container_name: liquibase
    depends_on:
      cassandra-init:
        condition: service_completed_successfully
    volumes:
      - ../liquibase/lib:/liquibase/lib
      - ../liquibase/changelog:/liquibase/changelog
    command:
      - "--url=jdbc:cassandra://cassandra:9042/product_model_ks?localdatacenter=datacenter1&compliancemode=Liquibase"
      - "--changeLogFile=changelog/master.xml"
      - "--driver=com.ing.data.cassandra.jdbc.CassandraDriver"
      - "update"

  ktor-rest:
#    build:
#      context: ../
#      dockerfile: docker/Dockerfile-app-ktor
    image: app-ktor-rest:latest
    container_name: app-ktor-rest
    ports:
      - "8081:8081"
    depends_on:
      liquibase:
        condition: service_completed_successfully
    environment:
      CASSANDRA_CONTACT_POINT: cassandra
      CASSANDRA_PORT: 9042
      CASSANDRA_KEYSPACE: product_model_ks
      PM_HOST: cassandra
      PM_PORT: 9042