ktor:
  application:
    modules:
      - com.product.model.ApplicationKt.module
  deployment:
    port: 8081

product-model:
  repository:
    test: "inmemory"
    prod: "$DB_TYPE_PROD:inmemory"
    cassandra:
      keyspace: "$PM_KEYSPACE:product-model"
      host: "$PM_HOST:localhost"
      port: "$PM_PORT:9042"
      user: "$PM_USER:cassandra"
      pass: "$PM_PASS:cassandra"